#!/usr/bin/env bash
# Extracts a lean src/data/usage.ts from the AI token-usage heatmap export.
# Regenerate the export, then run: ./scripts/build-usage.sh [path-to-export.json]
set -euo pipefail

SRC="${1:-$HOME/heatmap-last-year.json}"
OUT="src/data/usage.ts"
mkdir -p "$(dirname "$OUT")"

DATA=$(jq -c '
  .providers[0] as $p |
  {
    start: "2025-06-28",
    end: .end,
    totalTokens: ([$p.daily[].total] | add),
    activeDays: ([$p.daily[] | select(.total > 0)] | length),
    longestStreak: $p.insights.streaks.longest,
    currentStreak: $p.insights.streaks.current,
    mostUsedModel: { name: $p.insights.mostUsedModel.name, total: $p.insights.mostUsedModel.tokens.total },
    recentModel: { name: $p.insights.recentMostUsedModel.name, total: $p.insights.recentMostUsedModel.tokens.total },
    maxDay: ($p.daily | max_by(.total) | { date, total }),
    daily: ([$p.daily[] | {
      date,
      total,
      models: ([(.breakdown // [])[] | { name: .name, total: .tokens.total }] | sort_by(-.total) | .[0:5])
    }] | sort_by(.date))
  }
' "$SRC")

{
  echo "// Generated by scripts/build-usage.sh from the AI token-usage heatmap export."
  echo ""
  echo "export type UsageModel = { name: string; total: number };"
  echo "export type UsageDay = { date: string; total: number; models: UsageModel[] };"
  echo "export type UsageData = {"
  echo "  start: string;"
  echo "  end: string;"
  echo "  totalTokens: number;"
  echo "  activeDays: number;"
  echo "  longestStreak: number;"
  echo "  currentStreak: number;"
  echo "  mostUsedModel: UsageModel;"
  echo "  recentModel: UsageModel;"
  echo "  maxDay: { date: string; total: number };"
  echo "  daily: UsageDay[];"
  echo "};"
  echo ""
  echo "export const USAGE: UsageData = $DATA;"
} > "$OUT"

echo "wrote $OUT ($(echo "$DATA" | jq '.daily | length') days)"
