#!/usr/bin/env bash
# Regenerates src/data/prs.ts from real GitHub PR data.
# Excludes committed drizzle migration artifacts (journals/snapshots/sql) from
# the diff counts and the chart, since those are generated noise.
# Usage: ./scripts/fetch-prs.sh   (requires gh auth)
set -euo pipefail

OUT="src/data/prs.ts"
mkdir -p "$(dirname "$OUT")"

# jq filter: drop any file under a drizzle/ directory.
ND='[.[] | select(.filename | test("(^|/)drizzle/") | not)]'

{
  echo "// Generated by scripts/fetch-prs.sh — real PR data for the 'latest' section."
  echo "// drizzle migration files are excluded from counts + chart. re-run to refresh."
  echo ""
  echo "export type Pr = {"
  echo "  title: string;"
  echo "  area: string;"
  echo "  repo: string;"
  echo "  number: number;"
  echo "  url: string;"
  echo "  additions: number;"
  echo "  deletions: number;"
  echo "  changedFiles: number;"
  echo "  commits: number;"
  echo "  mergedAt: string;"
  echo "  series: number[];"
  echo "};"
  echo ""
  echo "export const PRS: Pr[] = ["
} > "$OUT"

emit() {
  local repo="$1" num="$2" area="$3" title="$4" link="${5:-}"
  [ -z "$link" ] && link="https://github.com/useautumn/$repo/pull/$num"

  local files meta
  files=$(gh api --paginate "repos/useautumn/$repo/pulls/$num/files?per_page=100" | jq -s 'add')
  meta=$(gh api "repos/useautumn/$repo/pulls/$num" --jq '{commits,merged_at}')

  {
    echo "  {"
    echo "    title: \"$title\","
    echo "    area: \"$area\","
    echo "    repo: \"useautumn/$repo\","
    echo "    number: $num,"
    echo "    url: \"$link\","
    echo "    additions: $(echo "$files" | jq "$ND | [.[].additions] | add // 0"),"
    echo "    deletions: $(echo "$files" | jq "$ND | [.[].deletions] | add // 0"),"
    echo "    changedFiles: $(echo "$files" | jq "$ND | length"),"
    echo "    commits: $(echo "$meta" | jq -r '.commits'),"
    echo "    mergedAt: \"$(echo "$meta" | jq -r '.merged_at')\","
    echo "    series: $(echo "$files" | jq -c "$ND | [.[].additions]"),"
    echo "  },"
  } >> "$OUT"
}

emit autumn   1820 "external psps" "revenuecat oauth, managed products + managed integrations"
emit autumn   1716 "external psps" "migrate vercel marketplace to attach v2"
emit terraform 50  "analytics"    "lakehouse etl pipeline" "https://docs.useautumn.com/documentation/lakehouse/overview"
emit autumn   1895 "auth"         "per-customer jwts" "https://docs.useautumn.com/api-reference/keys/mintKey"

echo "];" >> "$OUT"
echo "wrote $OUT"
