#!/usr/bin/env python3
# Merges the freshly generated src/data/usage.ts with the version committed at
# HEAD, keeping the higher per-day total. Harness log retention (e.g. transcript
# cleanup) can only ever lose tokens, so a day's committed count is a floor.
import json
import subprocess
from datetime import date, timedelta

OUT = "src/data/usage.ts"


def load(src: str) -> dict:
    obj = src.split("export const USAGE: UsageData = ", 1)[1].rstrip().rstrip(";")
    return json.loads(obj)


new = load(open(OUT).read())
head = subprocess.run(
    ["git", "show", f"HEAD:{OUT}"], capture_output=True, text=True
)
if head.returncode != 0:
    print("merge-usage: no committed usage.ts at HEAD, keeping fresh scan as-is")
    raise SystemExit(0)
old = load(head.stdout)

merged = {d["date"]: d for d in old["daily"]}
for d in new["daily"]:
    if d["date"] not in merged or d["total"] > merged[d["date"]]["total"]:
        merged[d["date"]] = d
daily = sorted(merged.values(), key=lambda d: d["date"])

active = [d for d in daily if d["total"] > 0]
longest = cur = 0
prev = None
for d in active:
    dt = date.fromisoformat(d["date"])
    cur = cur + 1 if prev is not None and dt - prev == timedelta(days=1) else 1
    longest = max(longest, cur)
    prev = dt
current = 0
active_set = {d["date"] for d in active}
dt = date.fromisoformat(new["end"])
while dt.isoformat() in active_set:
    current += 1
    dt -= timedelta(days=1)

maxday = max(daily, key=lambda d: d["total"])
data = {
    "start": new["start"],
    "end": new["end"],
    "totalTokens": sum(d["total"] for d in daily),
    "activeDays": len(active),
    "longestStreak": longest,
    "currentStreak": current,
    "mostUsedModel": new["mostUsedModel"],
    "recentModel": new["recentModel"],
    "maxDay": {"date": maxday["date"], "total": maxday["total"]},
    "daily": daily,
}

ts = f"""// Generated by scripts/build-usage.sh from the AI token-usage heatmap export.

export type UsageModel = {{ name: string; total: number }};
export type UsageDay = {{ date: string; total: number; models: UsageModel[] }};
export type UsageData = {{
  start: string;
  end: string;
  totalTokens: number;
  activeDays: number;
  longestStreak: number;
  currentStreak: number;
  mostUsedModel: UsageModel;
  recentModel: UsageModel;
  maxDay: {{ date: string; total: number }};
  daily: UsageDay[];
}};

export const USAGE: UsageData = {json.dumps(data, separators=(",", ":"))};
"""
open(OUT, "w").write(ts)
restored = data["totalTokens"] - new["totalTokens"]
print(f"merge-usage: total {data['totalTokens']:,} (+{restored:,} restored from HEAD)")
