// Generated by scripts/fetch-prs.sh — real PR data for the 'latest' section.
// drizzle migration files are excluded from counts + chart. re-run to refresh.

export type Pr = {
  title: string;
  area: string;
  repo: string;
  number: number;
  url: string;
  additions: number;
  deletions: number;
  changedFiles: number;
  commits: number;
  mergedAt: string;
  series: number[];
};

export const PRS: Pr[] = [
  {
    title: "revenuecat oauth, managed products + managed integrations",
    area: "external psps",
    repo: "useautumn/autumn",
    number: 1820,
    url: "https://github.com/useautumn/autumn/pull/1820",
    additions: 10434,
    deletions: 715,
    changedFiles: 115,
    commits: 16,
    mergedAt: "2026-06-05T15:44:00Z",
    series: [2, 79, 32, 77, 378, 57, 153, 6, 117, 8, 179, 72, 206, 586, 3, 295, 284, 10, 143, 75, 171, 277, 11, 165, 165, 165, 22, 193, 3, 101, 232, 54, 6, 1, 9, 52, 24, 126, 21, 152, 12, 298, 94, 57, 1, 81, 114, 133, 5, 114, 333, 6, 26, 11, 8, 2, 2, 9, 17, 7, 5, 4, 69, 2, 63, 39, 58, 330, 116, 2, 20, 1, 2, 68, 78, 46, 14, 22, 5, 2, 375, 50, 65, 160, 66, 109, 66, 126, 140, 401, 185, 138, 126, 63, 61, 87, 127, 7, 26, 9, 14, 45, 63, 42, 61, 2, 154, 0, 73, 47, 210, 209, 139, 0, 0],
  },
  {
    title: "migrate vercel marketplace to attach v2",
    area: "external psps",
    repo: "useautumn/autumn",
    number: 1716,
    url: "https://github.com/useautumn/autumn/pull/1716",
    additions: 4864,
    deletions: 850,
    changedFiles: 85,
    commits: 25,
    mergedAt: "2026-05-26T16:12:28Z",
    series: [0, 2, 16, 18, 37, 7, 5, 5, 7, 129, 45, 8, 85, 23, 121, 8, 36, 112, 37, 35, 16, 47, 216, 151, 21, 4, 2, 7, 10, 1, 14, 5, 111, 30, 5, 2, 70, 4, 11, 1, 44, 12, 53, 154, 130, 0, 0, 0, 1, 0, 429, 136, 150, 111, 170, 299, 324, 277, 39, 106, 86, 81, 40, 10, 14, 7, 38, 47, 9, 23, 30, 11, 5, 2, 13, 1, 3, 3, 73, 49, 94, 27, 0, 168, 131],
  },
  {
    title: "lakehouse etl pipeline",
    area: "analytics",
    repo: "useautumn/terraform",
    number: 50,
    url: "https://docs.useautumn.com/documentation/lakehouse/overview",
    additions: 1083,
    deletions: 1,
    changedFiles: 21,
    commits: 2,
    mergedAt: "2026-06-08T15:29:06Z",
    series: [1, 3, 44, 112, 6, 20, 50, 168, 6, 11, 50, 32, 145, 96, 21, 37, 66, 29, 26, 126, 34],
  }
];
